'use strict';

// 菜单栏与更新提示的中英文词典。语言名保持各自语言的原生写法，便于识别。

const MENU_LANGUAGES = Object.freeze(['zh-CN', 'en-US']);

const MENU_LABELS = Object.freeze({
  'zh-CN': Object.freeze({
    file: '文件',
    new: '新建',
    newWindow: '新建窗口',
    open: '打开…',
    save: '保存',
    saveAs: '另存为…',
    print: '打印…',
    export: '导出',
    pdf: 'PDF…',
    html: 'HTML…',
    recent: '最近打开',
    clearRecent: '清除最近打开记录',
    noRecent: '（暂无记录）',
    quit: '退出',
    close: '关闭窗口',
    edit: '编辑',
    undo: '撤销',
    redo: '重做',
    cut: '剪切',
    copy: '复制',
    paste: '粘贴',
    selectAll: '全选',
    find: '查找…',
    findNext: '查找下一个',
    findPrevious: '查找上一个',
    replace: '替换…',
    paragraph: '段落',
    text: '正文',
    headingLevel: '级标题',
    blockQuote: '引用块',
    bulletList: '无序列表',
    orderedList: '有序列表',
    taskList: '任务列表',
    codeBlock: '代码块',
    format: '格式',
    bold: '加粗',
    italic: '斜体',
    strike: '删除线',
    inlineCode: '行内代码',
    insertLink: '插入链接…',
    insert: '插入',
    image: '图片…',
    link: '链接…',
    table: '表格…',
    horizontalRule: '水平分割线',
    dateTime: '日期时间',
    view: '视图',
    sidebar: '显示/隐藏文件侧边栏',
    outline: '大纲面板',
    focus: '专注模式',
    toggleMode: '切换源码/所见即所得',
    cycleTheme: '切换主题',
    theme: '主题',
    followSystem: '跟随系统',
    light: '浅色',
    cream: '奶油白',
    dark: '暗色',
    language: '界面语言',
    chinese: '中文',
    english: 'English',
    autoSave: '自动保存',
    fontSize: '字号',
    editorFont: '正文字体',
    followTheme: '跟随主题',
    sans: '无衬线',
    serif: '衬线',
    mono: '等宽',
    zoomIn: '放大',
    zoomOut: '缩小',
    resetZoom: '重置缩放',
    fullscreen: '全屏',
    help: '帮助',
    checkUpdates: '检查更新…',
    automaticUpdateCheck: '启动时自动检查更新',
    guide: '操作说明',
    about: '关于 Markdown阅读器',
    upToDateTitle: '检查更新',
    upToDateMessage: '当前已是最新版本',
    currentVersion: '当前版本',
    latestVersion: 'GitHub 最新稳定发布',
    updateTitle: '发现新版本',
    updateMessage: 'Markdown阅读器 v{version} 已发布',
    releaseNotes: '发布说明',
    viewRelease: '查看发布页',
    later: '暂不更新',
    updateActionHint: '点击“查看发布页”会打开 GitHub Releases 页面。应用不会自动下载或安装更新。',
    checkFailedTitle: '检查更新失败',
    checkFailedMessage: '无法获取 GitHub 最新发布',
    checkFailedDetail: '请检查网络连接或稍后在“帮助 → 检查更新…”中重试。'
  }),
  'en-US': Object.freeze({
    file: 'File',
    new: 'New',
    newWindow: 'New Window',
    open: 'Open…',
    save: 'Save',
    saveAs: 'Save As…',
    print: 'Print…',
    export: 'Export',
    pdf: 'PDF…',
    html: 'HTML…',
    recent: 'Recent',
    clearRecent: 'Clear Recent',
    noRecent: '(Empty)',
    quit: 'Quit',
    close: 'Close Window',
    edit: 'Edit',
    undo: 'Undo',
    redo: 'Redo',
    cut: 'Cut',
    copy: 'Copy',
    paste: 'Paste',
    selectAll: 'Select All',
    find: 'Find…',
    findNext: 'Find Next',
    findPrevious: 'Find Previous',
    replace: 'Replace…',
    paragraph: 'Paragraph',
    text: 'Text',
    headingLevel: ' Heading',
    blockQuote: 'Blockquote',
    bulletList: 'Bullet List',
    orderedList: 'Numbered List',
    taskList: 'Task List',
    codeBlock: 'Code Block',
    format: 'Format',
    bold: 'Bold',
    italic: 'Italic',
    strike: 'Strikethrough',
    inlineCode: 'Inline Code',
    insertLink: 'Insert Link…',
    insert: 'Insert',
    image: 'Image…',
    link: 'Link…',
    table: 'Table…',
    horizontalRule: 'Horizontal Rule',
    dateTime: 'Date & Time',
    view: 'View',
    sidebar: 'Show/Hide File Sidebar',
    outline: 'Outline Panel',
    focus: 'Focus Mode',
    toggleMode: 'Toggle Source/WYSIWYG',
    cycleTheme: 'Cycle Theme',
    theme: 'Theme',
    followSystem: 'Follow System',
    light: 'Light',
    cream: 'Cream White',
    dark: 'Dark',
    language: 'Interface Language',
    chinese: '中文',
    english: 'English',
    autoSave: 'Auto Save',
    fontSize: 'Font Size',
    editorFont: 'Body Font',
    followTheme: 'Follow Theme',
    sans: 'Sans',
    serif: 'Serif',
    mono: 'Monospace',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    resetZoom: 'Reset Zoom',
    fullscreen: 'Full Screen',
    help: 'Help',
    checkUpdates: 'Check for Updates…',
    automaticUpdateCheck: 'Check Automatically on Startup',
    guide: 'User Guide',
    about: 'About Markdown Reader',
    upToDateTitle: 'Check for Updates',
    upToDateMessage: 'You are up to date',
    currentVersion: 'Current version',
    latestVersion: 'Latest GitHub stable release',
    updateTitle: 'Update Available',
    updateMessage: 'Markdown Reader v{version} is available',
    releaseNotes: 'Release notes',
    viewRelease: 'View Release',
    later: 'Not Now',
    updateActionHint: '“View Release” opens the GitHub Releases page. The app does not download or install updates automatically.',
    checkFailedTitle: 'Update Check Failed',
    checkFailedMessage: 'Unable to get the latest GitHub release',
    checkFailedDetail: 'Check your network connection, then retry from Help → Check for Updates….'
  })
});

function getMenuLabels(language = 'zh-CN') {
  return MENU_LABELS[MENU_LANGUAGES.includes(language) ? language : 'zh-CN'];
}

function formatMenuLabel(template, values = {}) {
  return template.replace(/\{(\w+)\}/g, (match, key) => (
    Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : match
  ));
}

module.exports = {
  MENU_LANGUAGES,
  MENU_LABELS,
  formatMenuLabel,
  getMenuLabels
};
